exclude: ['README.md', 'preview.sh', 'Gemfile', 'Gemfile.lock']

# Used to generate the site
title: "Good Soup"
title_short: "Good Soup"
email: "hey@goodsoup.com"
description: "We serve fresh piping hot soup every Wednesday from 10:00PM - 11:30PM on 90.5FM WHRW Binghamton."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://goodsoup.com" # the base hostname & protocol for your site
# itunes_url: "https://itunes.apple.com/us/podcast/xxx"

# itunes_id creates a smart banner on Safari in iOS prompting
# visitors to subscribe
# Uncomment next line to enable
#itunes_id: xxx # The ID is after the last slash in itunes_url above minus the letters "id"
# twitter_username: yourtwitter
# twitter_podcastname: yourpodcasttwitter

# For the SEO tag
seo:
  name: "Good Soup"
  type: "CreativeWork"
  about: "We serve fresh piping hot soup every Wednesday from 10:00PM - 11:30PM on 90.5FM WHRW Binghamton."
  person: "DJ Retr0"

# Used to generate the iTunes-compatible RSS feed
podcast:
  owner:
    name: DJ Retr0
    email: hey@goodsoup.com
  explicit: "no" # Change to yes if you're a potty mouth
  image: /img/logo.png # iTunes requires 2,000 pixel art
  keywords: "music WHRW Binghamton"
  categories:
    - category: "Music Commentary"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Plugins
plugins:
  - jekyll-seo-tag
